version: '3.5'

services:

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: leofontolan/fc-nginx-node:node
    container_name: node
    volumes:
      - ./node:/usr/src/app
    networks:
      - nginx-node-net
    tty: true

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - nginx-node-net

  nginx:
    build:
        context: ./nginx
        dockerfile: Dockerfile
    image: leofontolan/fc-nginx-node:nginx
    container_name: nginx
    networks:
      - nginx-node-net
    ports:
       - "8080:80"

networks:
  nginx-node-net:
    driver: bridge